### ISSUE TITLE
SessionRequest message - the ECDH public key field in handshake

### ISSUE THREAD

**Issue by janj-epam** [LykkeBusiness/openvasp-message-samples#1]
The whitepaper in section 7.3.2 says that the "ecdhpk" field should be a 256-bit long hex value. In the example message provided, the key is longer than that, exactly 130 hex characters (520 bits), which suggests it is the standard Ethereum public key (plus the "04" byte at the front indicating uncompressed key). So am I right to assume that the whitepaper is wrong here (and therefore needs to be updated), or is it right and we should first somehow compress that key to 256-bits before serializing it into JSON and sending out?

**Comment by NovichikhinAlexey** [comment]
Hello @janj-epam 

we already discuss topic about keys here: https://github.com/OpenVASP/openvasp-csharp-client/issues/20#issuecomment-608861877

In general, I can say what we should remove from the WhitePaper requirement to 256 bit.
Because ECDH public key can be in 3 view: 
* 02-compressed - 32 byte
* 03-compressed 0 32 byte
* 04-uncompressed - 64 byte
+ in the first byte of the public key we should have type (02, 03, 04).

If we try use Ethereum public key then usually in the Ethereum library people use only 04-uncompressed public keys. To generate 32-byte key need to use special library for encryption.

Byt anyway all 3 types of keys are valid and can be applied to the encryption algorithm and better to say what type of public-key it is up to the client and it is should be hex with 33 of 65 byte

**Comment by Felix0301** [comment]
I agree that the 256-bit requirement must be removed, since it is simply impossible to fit a ECDH in 256 bit (even compressed it is 33 byte). However it needs to be discussed/decided whether we support compressed (33 Bytes) or uncompressed (65 Bytes) or raw (64 Bytes) or all three or two of the three.

**Comment by Felix0301** [comment]
I suggest to roll with compressed keys only (33 Byte) to avoid variable length field and ambiguity whereever possible.
